.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH orgsidian-index-init 1  "init " 
.SH NAME
orgsidian\-index\-init \- Create + populate the index for a vault (incremental on re\-run)
.SH SYNOPSIS
\fBorgsidian index init\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVAULT\fR> 
.SH DESCRIPTION
Create + populate the index for a vault (incremental on re\-run)
.SH OPTIONS
.TP
\fB\-\-json\fR
Emit a single JSON object to stdout instead of human\-readable text (no progress lines)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVAULT\fR>
Path to the vault root directory to index
